# Import the modules

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
%matplotlib inline

In [8]:
from sklearn.model_selection import train_test_split

#  

# Data collection

In [97]:
suv_data = pd.read_csv("Social_Network_Ads.csv")
suv_data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

#  

# Define the dependent and independent variables

In [12]:
x = suv_data.iloc[:,[2,3]].values
y = suv_data.iloc[:,4].values
print(x[:5],y[:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]] [0 0 0 0 0]


#  

# Split the dataset

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

#    

# Standardize the data

In [69]:
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

C:\Users\santosh\Miniconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\santosh\Miniconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\santosh\Miniconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


#  

# Logistic Regression Model

In [70]:
logisticmodel = LogisticRegression(solver='lbfgs')
logisticmodel.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

#  

# Prediction of x_test

In [71]:
prediction = logisticmodel.predict(x_test)

In [72]:
prediction[:5]

array([0, 1, 0, 1, 0], dtype=int64)

#  

# Prediction of a single own data

In [103]:
test = np.array([[20,200000]]).astype(float)

In [104]:
test = sc.transform(test)

In [105]:
test

array([[-1.65978287,  3.81248992]])

In [106]:
test_prediction = logisticmodel.predict(test)

In [107]:
test_prediction

array([1], dtype=int64)

#  

# Accuracy Check

In [73]:
accuracy = accuracy_score(y_test,prediction)
print(accuracy*100)

86.0
